version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-sam-mojix"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vnxn3l4mfrpk"
s3_prefix = "hello-sam-mojix"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
